### ISSUE TITLE
[COR1010] standard output decoding issue

### ISSUE THREAD

**Issue by limbs713** [RangHo/sogang-courses#9]
## 문제가 있는 코드 정보

기초인공지능프로그래밍
grader.py

## 문제 설명

학생들의 코드를 저장한 폴더의 파일 경로에 한글이 포함되면 DecodeError가 발생합니다.

### 문제를 재현하는 방법

파일 경로에 한글이 포함된 폴더가 포함되어 있으면 발생할 수 있습니다.

**Comment by RangHo** [comment]
이 이슈는 파일명의 문제도 있을 수 있으나 `run` 함수의 `decode`에서 오류가 발생하는 것으로 미루어 볼 때, 터미널 출력의 인코딩이 유니코드가 아닐 가능성이 있습니다.

오류 메시지는 [여기](https://pastebin.com/PKmPH9bq)를 참고하세요.

**Comment by RangHo** [comment]
일반 리눅스에서 해당 문제를 재현하려면 `ko_KR.EUC-KR` 로케일을 생성한 뒤 `EUC-KR`을 적용한 셸에서 해당 프로그램을 실행합니다.

```sh
# Generate ko_KR.EUC-KR locale
sudo sed -i .bak 's/# ko_KR.EUC-KR/ko_KR.EUC-KR/g' /etc/locale.gen
sudo locale-gen

# Restart shell here

# Create new shell with EUC-KR
env LANG="ko_KR.EUC-KR" sh

# Try running the code
python /path/to/grade.py /path/to/submissions --answer-code /path/to/answer.py # ...
```

**Comment by RangHo** [comment]
아직 인코딩 문제가 발생합니다. `0xBC`가 유니코드 코드포인트가 아니라는 것이 문제인 듯 한데, 파일이 EUC-KR로 저장되어 있으나 터미널 인코딩은 UTF-8일 가능성이 있습니다. 추가적인 확인이 필요합니다.
